apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: p2p
  namespace: devops-tools
spec:
  generators:
  - list:
      elements:
      - name: qbittorrent
        path: ./qbittorrent
        helmRelease: ""
        helmChartUrl: ""
        helmArgs: -f values.yaml
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/home-kops/k8s-p2p.git
        targetRevision: main
        path: '{{path}}'
        plugin:
          name: argocd-vault-plugin-helm
          env:
          - name: HELM_RELEASE
            value: '{{helmRelease}}'
          - name: HELM_CHART
            value: '{{helmChartUrl}}'
          - name: HELM_ARGS
            value: '{{helmArgs}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: p2p
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
