apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring-helm
  namespace: devops-tools
spec:
  generators:
  - list:
      elements:
      - name: loki
        path: ./loki
        helmRelease: loki
        helmChartUrl: https://grafana.github.io/helm-charts
        helmChartVersion: 6.30.1
      - name: prometheus
        path: ./prometheus
        helmRelease: prometheus
        helmChartUrl: https://prometheus-community.github.io/helm-charts
        helmChartVersion: 27.22.0
      - name: crowdsec
        path: ./crowdsec
        helmRelease: crowdsec
        helmChartUrl: https://crowdsecurity.github.io/helm-charts
        helmChartVersion: 0.19.3
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      sources:
      - repoURL: '{{helmChartUrl}}'
        chart: '{{helmRelease}}'
        targetRevision: '{{helmChartVersion}}'
        helm:
          valueFiles:
          - '$values/{{path}}/values.yaml'
      - repoURL: https://github.com/home-kops/k8s-monitoring.git
        targetRevision: main
        ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: monitoring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
