apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gh-arc-controller
  namespace: devops-tools
spec:
  source:
    path: .
    repoURL: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller
    targetRevision: 0.12.1
  destination:
    server: https://kubernetes.default.svc
    namespace: devops-tools
