apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets
  namespace: devops-tools
spec:
  generators:
    - list:
        elements:
          - name: external-secrets
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/home-kops/k8s-homelab.git
        targetRevision: main
        path: './external-secrets/{{name}}'
        plugin:
          name: infra-envsubst
      destination:
        server: https://kubernetes.default.svc
        namespace: external-secrets
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        managedNamespaceMetadata:
          labels:
            pod-security.kubernetes.io/enforce: baseline
            pod-security.kubernetes.io/enforce-version: latest
            pod-security.kubernetes.io/audit: restricted
            pod-security.kubernetes.io/audit-version: latest
        syncOptions:
          - CreateNamespace=true
