apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: network
  namespace: devops-tools
spec:
  generators:
    - list:
        elements:
          - name: traefik
            ignoreDifferences: []
          - name: certmanager
            ignoreDifferences: []
          - name: metallb
            ignoreDifferences: []
          - name: istio
            ignoreDifferences:
            - group: admissionregistration.k8s.io
              kind: ValidatingWebhookConfiguration
              name: istiod-default-validator
              jqPathExpressions:
              - .webhooks[] | select(.name == "validation.istio.io") | .failurePolicy
            - group: admissionregistration.k8s.io
              kind: ValidatingWebhookConfiguration
              name: istio-validator-network
              jqPathExpressions:
              - .webhooks[] | select(.name == "rev.validation.istio.io") | .failurePolicy
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/home-kops/k8s-homelab.git
        targetRevision: main
        path: './network/{{name}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: network
      ignoreDifferences: {{ ignoreDifferences | toJson }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        managedNamespaceMetadata:
          labels:
            pod-security.kubernetes.io/audit: restricted
            pod-security.kubernetes.io/audit-version: latest
        syncOptions:
          - CreateNamespace=true
