apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: network
  namespace: devops-tools
spec:
  generators:
    - list:
        elements:
          - name: traefik
          - name: certmanager
          - name: metallb
          - name: istio
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/home-kops/k8s-homelab.git
        targetRevision: main
        path: './network/{{name}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: network
      ignoreDifferences:
      - group: admissionregistration.k8s.io
        kind: ValidatingWebhookConfiguration
        name: istiod-default-validator
        namespace: network
        jsonPointers:
        - /webhooks/0/failurePolicy
      - group: admissionregistration.k8s.io
        kind: ValidatingWebhookConfiguration
        name: istio-validator-network
        namespace: network
        jsonPointers:
        - /webhooks/0/failurePolicy
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        managedNamespaceMetadata:
          labels:
            pod-security.kubernetes.io/audit: restricted
            pod-security.kubernetes.io/audit-version: latest
        syncOptions:
          - CreateNamespace=true
