apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: misc
  namespace: devops-tools
spec:
  generators:
  - list:
      elements:
      - name: homepage
        path: ./homepage
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/home-kops/k8s-misc.git
        targetRevision: main
        path: '{{path}}'
        plugin:
          name: argocd-vault-plugin-helm
          env:
          - name: HELM_ARGS
            value: -f values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: misc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
