apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: network
  namespace: devops-tools
spec:
  generators:
  - list:
      elements:
      - name: traefik
        path: ./traefik
      - name: certmanager
        path: ./certmanager
      - name: metallb
        path: ./metallb
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/home-kops/k8s-network.git
        targetRevision: main
        path: '{{path}}'
        plugin:
          name: argocd-vault-plugin-kustomize
      destination:
        server: https://kubernetes.default.svc
        namespace: network
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
