apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: p2p
  namespace: devops-tools
spec:
  generators:
    - list:
        elements:
          - name: jackett
          - name: slskd
          - name: qbittorrent
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/home-kops/k8s-p2p.git
        targetRevision: main
        path: '{{name}}'
        plugin:
          name: argocd-vault-plugin-kustomize
      destination:
        server: https://kubernetes.default.svc
        namespace: p2p
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        managedNamespaceMetadata:
          labels:
            pod-security.kubernetes.io/audit: restricted
            pod-security.kubernetes.io/audit-version: latest
        syncOptions:
          - CreateNamespace=true
